/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderInput {
  'deliveryAddress' : string,
  'items' : Array<LineItem>,
  'contactPhone' : string,
}
export interface LineItem {
  'nameSnapshot' : string,
  'unitPriceSnapshot' : number,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface Order {
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'createdAt' : bigint,
  'orderId' : bigint,
  'userPrincipal' : Principal,
  'items' : Array<LineItem>,
  'contactPhone' : string,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'outForDelivery' : null } |
  { 'placed' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'availability' : boolean,
  'imageUrl' : [] | [string],
  'category' : string,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[CreateOrderInput], bigint>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrderStatus' : ActorMethod<[bigint], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];