/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineItem = IDL.Record({
  'nameSnapshot' : IDL.Text,
  'unitPriceSnapshot' : IDL.Float64,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'items' : IDL.Vec(LineItem),
  'contactPhone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'availability' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
  'items' : IDL.Vec(LineItem),
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initProducts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'nameSnapshot' : IDL.Text,
    'unitPriceSnapshot' : IDL.Float64,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'items' : IDL.Vec(LineItem),
    'contactPhone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'availability' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
    'items' : IDL.Vec(LineItem),
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initProducts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };